version: "3.9"
services:
    minecraft:
        restart: always
        image: bitsfitr/minecraft-fabric:latest
        environment:
          - EULA=true
          - JAVA_OPTS=-Xmx4G -Xgcpolicy:balanced
        volumes:
            - ./data:/minecraft
        ports:
            - 25565:25565
            - 25575:25575
